# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3

parameters:
  run-build-styles-job:
    type: boolean
    default: false
  run-build-core-job:
    type: boolean
    default: false
  run-build-modsign-job:
    type: boolean
    default: false
  run-build-formbuilder-job:
    type: boolean
    default: false



jobs:
  build-styles:
    executor:
      name: android/android-machine
    when: << pipeline.parameters.run-build-styles-job >>
    resource_class: xlarge
    steps:
      - checkout
      - run: ./gradlew :styles:assembleRelease

  build-core:
    executor:
      name: android/android-machine
    when: << pipeline.parameters.run-build-core-job >>
    resource_class: xlarge
    steps:
      - checkout
      - run: ./gradlew :core:assembleRelease

  build-modsign:
    executor:
      name: android/android-machine
    when: << pipeline.parameters.run-build-modsign-job >>
    resource_class: xlarge
    steps:
      - checkout
      - run: ./gradlew :formbuilder:assembleRelease

  build-formbuilder:
    executor:
      name: android/android-machine
    when: << pipeline.parameters.run-build-formbuilder-job >>
    resource_class: xlarge
    steps:
      - checkout
      - run: ./gradlew :formbuilder:assembleRelease

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: 
    jobs:
      - build-styles
      - build-core:
        requires:
          - build-styles
      - build-modsign:
        requires:
          - build-core
      - build-formbuilder:
        requires:
          - build-core
