# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3

parameters:
  run-build-styles-job:
    type: boolean
    default: false
  run-build-core-job:
    type: boolean
    default: false
  run-build-modsign-job:
    type: boolean
    default: false
  run-build-formbuilder-job:
    type: boolean
    default: false



jobs:
  build_styles:
    executor:
      name: android/android-machine
    resource_class: 2xlarge+
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.run-build-styles-job >> ]
          steps:
            - checkout
            - run: ./gradlew :styles:assembleRelease

  build_core:
    executor:
      name: android/android-machine
    resource_class: 2xlarge+
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.run-build-core-job >> ]
          steps:
            - checkout
            - run: ./gradlew :core:assembleRelease

  build_modsign:
    executor:
      name: android/android-machine
    resource_class: 2xlarge+
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.run-build-modsign-job >> ]
          steps:
            - checkout
            - run: ./gradlew :modsign:assembleRelease

  build_formbuilder:
    executor:
      name: android/android-machine
    resource_class: 2xlarge+
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.run-build-formbuilder-job >> ]
          steps:
            - checkout
            - run: ./gradlew :formbuilder:assembleRelease

workflows:
  sample: 
    jobs:
      - build_styles:
          name: build_styles1
      - build_core:
          name: build_core1
          requires:
            - build_styles1
      - build_modsign:
          name: build_modsign
          requires:
            - build_core1
      - build_formbuilder:
          name: build_formbuilder
          requires:
            - build_core1
